CREATE TABLE IF NOT EXISTS EMPLOYEE_TB (
ID VARCHAR NOT NULL,
NAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
REGISTRATION VARCHAR(10) NOT NULL,
PHONE VARCHAR(30) NOT NULL,
BIRTH_DATE DATE NOT NULL,
PRIMARY KEY (ID),
UNIQUE (EMAIL),
UNIQUE (REGISTRATION),
UNIQUE (PHONE)
);

CREATE TABLE IF NOT EXISTS MANAGER_TB (
ID VARCHAR NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID) REFERENCES EMPLOYEE_TB (ID)
);

CREATE TABLE IF NOT EXISTS ASSISTANT_MANAGER_TB (
ID VARCHAR NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID) REFERENCES EMPLOYEE_TB (ID)
);

CREATE TABLE IF NOT EXISTS SALER_TB (
ID VARCHAR NOT NULL,
COMMISSION NUMERIC(20,2) NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID) REFERENCES EMPLOYEE_TB (ID)
);

CREATE TABLE IF NOT EXISTS CUSTOMER_TB (
ID VARCHAR NOT NULL,
DOCUMENT VARCHAR(20) NOT NULL,
NAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
PHONE VARCHAR(30) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PF_TB (
ID VARCHAR NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID) REFERENCES CUSTOMER_TB (ID)
);

CREATE TABLE IF NOT EXISTS PJ_TB (
ID VARCHAR NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID) REFERENCES CUSTOMER_TB (ID)
);

CREATE TABLE IF NOT EXISTS SALE_TB (
ID VARCHAR NOT NULL,
DATE_TIME TIMESTAMP NOT NULL,
PAYMENT_TYPE VARCHAR(30) NOT NULL,
TOTAL NUMERIC(20,2) NOT NULL,
SALER_ID VARCHAR NOT NULL,
CUSTOMER_ID VARCHAR NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (SALER_ID) REFERENCES SALER_TB (ID),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_TB (ID)
);

CREATE TABLE IF NOT EXISTS BRAND_TB (
ID VARCHAR NOT NULL,
NAME VARCHAR(30) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (NAME)
);

CREATE TABLE IF NOT EXISTS MODEL_TB (
ID VARCHAR NOT NULL,
NAME VARCHAR(30) NOT NULL,
BRAND_ID VARCHAR NOT NULL,
PRIMARY KEY (ID),
UNIQUE (NAME),
FOREIGN KEY (BRAND_ID) REFERENCES BRAND_TB (ID)
);

CREATE TABLE IF NOT EXISTS VEHICLE_TB (
ID VARCHAR NOT NULL,
PLATE VARCHAR(30) NOT NULL,
TRANSMISSION_TYPE VARCHAR(30) NOT NULL,
PRICE NUMERIC(20,2) NOT NULL,
MODEL_ID VARCHAR NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (MODEL_ID) REFERENCES MODEL_TB (ID)
);

CREATE TABLE IF NOT EXISTS CAR_TB (
ID VARCHAR NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID) REFERENCES VEHICLE_TB (ID)
);

CREATE TABLE IF NOT EXISTS MOTORCYCLE_TB (
ID VARCHAR NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID) REFERENCES VEHICLE_TB (ID)
);

CREATE TABLE IF NOT EXISTS SALE_VEHICLE_TB (
SALE_ID VARCHAR NOT NULL,
VEHICLE_ID VARCHAR NOT NULL,
QUANTITY INT NOT NULL,
PRIMARY KEY (SALE_ID, VEHICLE_ID),
FOREIGN KEY (SALE_ID) REFERENCES SALE_TB (ID),
FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE_TB (ID)
);

