# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Maven

on:
  push:
    branches: [ "development", "main" ]
  pull_request:
    branches: [ "development", "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout do código
        uses: actions/checkout@v4

    - name: Configurar cache do Maven
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: maven-cache-windows-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-cache-windows-
            - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Pode ser 'zulu', 'adopt', etc.
          java-version: '17'       # Mude para a versão que precisar
          cache: 'maven'

    - name: Construir o projeto com Maven
        run: mvn clean package

    - name: Executar testes
        run: mvn test
      
    # - uses: actions/checkout@v4
    # - name: Set up JDK 17
    #  uses: actions/setup-java@v4
    #  with:
    #    java-version: '17'
    #    distribution: 'temurin'
    #    cache: maven
    # - name: Build with Maven
    #  run: mvn package

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
